### ISSUE TITLE
Looping

### ISSUE THREAD

**Issue by chrisdostert** [opctl/specs#207]
### Reference
- [loop in javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration)

##### Option 1
 thoughts: 
   - extends existing definition format
   - not as declarative as 2 because you must define your own loop variables
```YAML
run:
  serial:
    - op:
        ref: github.com/opspec-pkgs/opspec.op.list-deps#1.0.0
        inputs:
          opDotYml: $(op/op.yml)
        outputs:
          deps:
    - forEach:
        items: $(deps)
        (dep):
          serial:
            - op:
                ref: github.com/opspec-pkgs/opspec.op.update-dep#1.0.0
                inputs:
                  opDotYml: $(op/op.yml)
                  dep:
```

##### Option 2
 thoughts: 
   - extends existing definition format

```YAML
run:
  serial:
    - name: listDeps
      op: 
        ref: github.com/opspec-pkgs/opspec.op.list-deps#1.0.0
        inputs:
          opDotYml: $(op/op.yml)
    - name: depUpdateLoop
      forEach: $(listDeps.deps)
      serial:
        - name: updateDep
          op: 
            ref: github.com/opspec-pkgs/opspec.op.update-dep#1.0.0
            inputs:
              opDotYml: $(op/op.yml)
              # $(depUpdateLoop.value) is "auto" property set to value of current loop iteration
              dep: $(depUpdateLoop.value)
```

##### Option 3
> leverages [Declarative concurrency](https://github.com/opspec-io/spec/issues/178)

 thoughts:
   - call hierarchy not human readable
```YAML
run:
  listDeps:
    op:
      ref: github.com/opspec-pkgs/opspec.op.list-deps#1.0.0
      inputs:
        opDotYml: $(op/op.yml)
  updateDep:
    startOn:
      any:
        $(listDeps.SUCCEEDED)
    forEach:
      items: $(listDeps.outputs.deps)
      (dep):
        op: 
          ref: github.com/opspec-pkgs/opspec.op.update-dep#1.0.0
          inputs:
            opDotYml: $(op/op.yml)
            dep:
```

**Comment by RoynKo** [comment]
```yaml
loop: 
  until:
    - ne 
    - eq
    - 
  forEach: $(listDeps.deps)
  index:
  value:
```

**Comment by RoynKo** [comment]
```yaml
loop: 
  forEach: $(listDeps.deps)
  index: $(i)
  value: $(v)
  until:
    eq:
    - Luis
    - ${name}
```

**Comment by chrisdostert** [comment]
```yaml
run:
  serial:
  # no outputs
  - loop: 
      forEach: $(someArrayInput)
      index: $(i)
      value: $(v)
      until:
      eq:
      - Luis
      - ${name}
    op: 
      ref: github.com/opspec-pkgs/opspec.op.update-dep#1.0.0
      inputs:
          opDotYml: $(op/op.yml)
          dep: $(value)
          
  # collected outputs
  - loop: 
      forEach: $(someArrayInput)
      index: $(i)
      value: $(v)
      until:
      eq:
      - Luis
      - ${name}
    op: 
      ref: github.com/opspec-pkgs/uuid.v4.generate#1.0.0
      outputs:
          $(someOutput[$(i)]): uuid

  # aggregate outputs
  - loop: 
      forEach: $(someArrayInput)
      index: $(i)
      value: $(v)
      until:
      eq:
      - Luis
      - ${name}
    op: 
      ref: github.com/opspec-pkgs/add#1.0.0
      inputs:
        values: [ $(v), $(total)]
      outputs:
          $(total): sum
```

**Comment by chrisdostert** [comment]
Proposal from @luisgarciaalanis  and @RoynKo 
```yaml
  for:
    index: index
    until: 
      - eq: [ $(index), 10] 
  foreach:
    values: [1,2,3,4]
    index: index
    value: name
    until: 
      - eq: [ $(index), 10] 
```

**Comment by chrisdostert** [comment]
ok this came back up again after we introduced parallel looping. Final syntax arrived at was:

```yaml
parallelLoop: # or serialLoop
  range: $(refToLoopableThing) # or [], or {} 
  until:
    - eq: [$(index), 2]
  vars:
    index: index
    key: key
    value: value
```
